name: CI.yml

on: push

env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  build-and-test:
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build and Test
      run: xcodebuild clean build test -workspace CathayApp.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 11" ONLY_ACTIVE_ARCH=YES